name: Build & Release macOS App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy pygame PyOpenGL

      - name: Build macOS bundle
        run: |
          pyinstaller --noconfirm --onedir \
            --add-data "beeGameFinal:beeGameFinal" \
            --add-data "resources:resources" \
            beeGameFinal/beeGame_main.py

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: BeeGame-macOS
          path: dist/**
